### ISSUE TITLE
Exception in thread "main" com.fulcrumgenomics.sopt.cmdline.ValidationException

### ISSUE THREAD

**Issue by rastiks** [nh13/bfx-examples#3]
Hi. We tryied to test the bfx-examples so far with no succes .... Could not find the way to continue ...  Could you help please ? Thnx . R.

sbt test ended with success... but ... 

machine:~/sbt_project_UMI$ java -jar bfx-examples/pipelines/target/scala-2.12/bfx-examples-pipelines.jar SingleStrandUmiSomaticVariantCalling --input-bam=/xdrive/umiPipeline/S29.bam -ref=/hg19/genome.fa --intervals=/xdrive/umiPipeline/E7000.bed --output=./test2.txt

[2018/07/31 11:32:51 | DagrCoreMain | Info] SingleStrandUmiSomaticVariantCalling failed. Elapsed time: 0.02 minutes.
Exception in thread "main" com.fulcrumgenomics.sopt.cmdline.ValidationException
	at dagr.core.cmdline.DagrCoreArgs.configure(DagrCoreMain.scala:142)
	at dagr.core.cmdline.DagrCoreMain.makeItSo(DagrCoreMain.scala:234)
	at dagr.core.cmdline.DagrCoreMain.makeItSoAndExit(DagrCoreMain.scala:213)
	at dagr.core.cmdline.DagrCoreMain$.main(DagrCoreMain.scala:55)
	at dagr.core.cmdline.DagrCoreMain.main(DagrCoreMain.scala)

CONFIG FILE : 
###############################################################################
# DAGR configuration file
################################################################################

# Some basic dagr configuration
dagr = {
  command-line-name = "bfx-examples-pipeline"
  path = ${PATH}             // tell dagr to search for executables using the system path by default
  package-list = ["com.nilshomer.bfx.examples"]
}

# Config variables that are used to set other paths
pipeline_dir     = /home/sbt_project_UMI/bfx-examples/pipeline/bin

# Task Configuration
picard.jar        = ${pipeline_dir}/picard.jar
fgbio.jar         = ${pipeline_dir}/fgbio.jar
bwa.executable    = ${pipeline_dir}/bwa
bwa-kit.dir       = ${pipeline_dir}/bwa.kit
vardictjava.dir   = ${pipeline_dir}/VarDictJava
bfx-examples-tools.jar = ${pipeline_dir}/bfx-examples-tools.jar

FYI : 
 /home/sbt_project_UMI/bfx-examples/pipeline/bin contains all the binary files (bwa, picard, fgbio, bfx-examples-tools) + directory bwa. kit with binaries  + directory VarDictJava with binaries (VarDict-1.5.4.jar)

**Comment by rastiks** [comment]
When I set the a dir as the output I was asked for a file : 

-machine:~/sbt_project_UMI$ java -jar bfx-examples/pipelines/target/scala-2.12/bfx-examples-pipelines.jar SingleStrandUmiSomaticVariantCalling --input-bam=/xdrive/umiPipeline/anntotated.bam -ref=/hg19/genome.fa --intervals=/xdrive/umiPipeline/E7000.bed --output=./test2

Exception in thread "main" java.lang.AssertionError: assertion failed: Cannot write file because it is a directory: /home/rasta/sbt_project_UMI/test2
	at scala.Predef$.assert(Predef.scala:219)
	at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile(Io.scala:119)
	at com.fulcrumgenomics.commons.io.IoUtil.assertCanWriteFile$(Io.scala:115)
	at com.fulcrumgenomics.commons.io.Io$.assertCanWriteFile(Io.scala:34)
	at com.nilshomer.bfx.examples.pipelines.SingleStrandUmiSomaticVariantCalling.<init>(SingleStrandUmiSomaticVariantCalling.scala:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fulcrumgenomics.commons.reflect.ReflectiveBuilder.build(ReflectiveBuilder.scala:161)
	at com.fulcrumgenomics.sopt.cmdline.CommandLineProgramParser.parseAndBuild(CommandLineProgramParser.scala:145)
	at com.fulcrumgenomics.sopt.cmdline.CommandLineParser.parseSubCommand(CommandLineParser.scala:311)
	at com.fulcrumgenomics.sopt.cmdline.CommandLineParser.parseCommandAndSubCommand(CommandLineParser.scala:411)
	at com.fulcrumgenomics.sopt.Sopt$.parseCommandAndSubCommand(Sopt.scala:156)
	at dagr.core.cmdline.DagrCoreMain.makeItSo(DagrCoreMain.scala:225)
	at dagr.core.cmdline.DagrCoreMain.makeItSoAndExit(DagrCoreMain.scala:213)
	at dagr.core.cmdline.DagrCoreMain$.main(DagrCoreMain.scala:55)
	at dagr.core.cmdline.DagrCoreMain.main(DagrCoreMain.scala)
